Dev milcom 1 d
CMU-SPEED/SMaLLFramework pull request #31
Opened 2024-09-10 20:20 UTC by UpasanaSridhar

Added interface calls for 1D layers used in Resnet_1D.
HOWEVER, the DepthwiseConv1D call results in a compiler error. I'm not sure why this is.

2024-09-19 22:48 UTC, mcmillan03 requested changes
I have left a number of comments that should be addressed before merging.

2024-09-19 22:48 UTC, mcmillan03 commented on CMakeLists.txt
> +if(CMAKE_UARCH STREQUAL "ZEN4")
ZEN4 is identical to ZEN2.  Switch to avx512 compiler flag?

2024-09-19 22:48 UTC, mcmillan03 commented on demo/CMakeLists.txt
> +foreach(layer_name ${LAYER_NAMES})
Assuming the non-fused functions are correct.  Unit tests could be created for fused functions and the results compared to the non-fused.  Having unit test instead of demos would be way better.

2024-09-19 22:48 UTC, mcmillan03 commented on demo/fused_block_driver.cpp
> +#include <math.h>
Add copyright block with an updated year.

2024-09-19 22:48 UTC, mcmillan03 commented on CMakeLists.txt
>  # elseif(CMAKE_UARCH STREQUAL "ARM")
Why does ARM-A72 have different compiler flags from the rest of the UARCH_ARM platforms.  If it is using the same backend shouldn't it use the same flags (i.e. flags are tied to the platform dir not the make target)?

2024-09-19 22:48 UTC, mcmillan03 commented on demo/mobilenet_v2_reshuffled.cpp
This file is not in the build and it has no material differences with mobile_net_reshuffled.cpp.  It can be deleted without losing anything new.

2024-09-19 22:48 UTC, mcmillan03 commented on demo/utils.h
>  #include <time.h>
this rdtsc function is not used anymore an can be deleted.

2024-09-19 22:48 UTC, mcmillan03 commented on demo/utils.h
>  #define print_cycles(time)                  \
It is not reporting cycles.

2024-09-19 22:48 UTC, mcmillan03 commented on demo/vggnet_reshuffled.cpp
This file is not part of the build and a non-shuffled vggnet is missing.  Should they be added?

2024-09-19 22:48 UTC, mcmillan03 commented on include/small.h
> +#include <small/fused_interface_abstract.hpp>
Should add an Issue to the github repo to discuss how fused layers get introduced completely in to the framework.  Including adding to interface.hpp and creating layer classes (if necessary).

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/TMP_WIP_abstract_layer.cpp
Should this file be deleted from the repo before merge to dev?  If contents needs to be saved, create a branch from dev after the merge and reintroduce these files.

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/TMP_WIP_fused_abstract_layer.cpp
Should this file be deleted from the repo before merge to dev? If contents needs to be saved, create a branch from dev after the merge and reintroduce these files.

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/abstract_layer.hpp
> +struct MappingParams
MappingParams is not used.  Delete?

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/abstract_layer.hpp
> +#define FLOAT_ABSTRACT_SINGLE_ELEMENT_UPSAMPLE_OP_END(out_step, op_type, op_class) \
This function does not appear to be used and starting with else if seems suspect.

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/abstract_layer.hpp
> +        H_o      = small::output_dim((I_h - H_full_index), _stride, F_h);
Why were these switched back to output_dim (from output_dim_new)? They are defined in utils.hpp.  Are they equivalent?  Is one better than the other?  We should settle on one implementation and delete the other.

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/abstract_layer.hpp
> +void fused_abstract_layer_1D(
Why do we need two functions. Are they both used?  Delete one if not.  This one is suspect as it calls kernel functions that are not 1D variants.

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/fused_interface.hpp
Delete an empty file....or add the missing declarations??

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/interface_abstract.hpp
I encourage you to look at the diffs for this file.  This is where I got rid of the unimplemented base case and explicit instantiation of the functions based on the BufferT type.  I am applied these changes to the other two new files as well.

2024-09-19 22:48 UTC, mcmillan03 commented on include/small/platforms/zen4/Buffer.hpp
zen4 platform is identical to zen2.  Should we delete it?

2024-09-24 13:34 UTC, mcmillan03 commented on demo/fused_block_driver.cpp
> +#include <math.h>
deferred

2024-09-24 13:48 UTC, mcmillan03 commented on include/small.h
> +#include <small/fused_interface_abstract.hpp>
Issue created to build a capabilities matrix showing implemented, tested, missing functionality.

2024-10-01 13:14 UTC, UpasanaSridhar commented on CMakeLists.txt
> +if(CMAKE_UARCH STREQUAL "ZEN4")
Adding compiler flag to register intent to develop avx512 kernels

2024-10-01 13:24 UTC, UpasanaSridhar commented on demo/mobilenet_v2_reshuffled.cpp
Removed this file

2024-10-01 13:31 UTC, UpasanaSridhar commented on demo/utils.h
>  #define print_cycles(time)                  \
print_cycles should print cycles not time.
Could replace with the print statement

2024-10-01 13:39 UTC, UpasanaSridhar commented on include/small/abstract_layer.hpp
> +#define FLOAT_ABSTRACT_SINGLE_ELEMENT_UPSAMPLE_OP_END(out_step, op_type, op_class) \
Intended to merge this with the previous macro

2024-10-02 16:18 UTC, mcmillan03 approved these changes

2024-10-08 02:01 UTC, merged